services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      target: ${DOCKER_TARGET:-local}
    ports:
      - 3000:3000
    tty: true
    command: npm run dev
    working_dir: /app
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ~/.cconfig/gcloud/application_default_credentials.json
        target: /application_default_credentials.json
      - type: volume
        source: reactflow_node_modules
        target: /app/node_modules
    environment:
      NODE_ENV: local
      PORT: 3000
      BIND_HOST: 0.0.0.0
      GOOGLE_APPLICATION_CREDENTIALS: './application_default_credentials.json'

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  reactflow_node_modules:
  mongo_data:
